  CosmosToS3LambdaFunction:
    module: src/cosmos_to_s3
    handler: handler.main
    runtime: python3.10
    name: cosmos-to-s3-lambda-function
    role: iamRoleCosmosToS3LambdaFunction
    environment:
      COSMOS_CONNECTION_STRING: ${ssm:COSMOS_CONNECTION_STRING~true}
      S3_BUCKET_NAME: ${ssm:S3_BUCKET_NAME~true}
      DATABASE_NAME: cosmicworks
      CONTAINER_NAME: products
