  CosmosToS3LambdaFunction:
    module: src/cosmos_to_s3
    handler: handler.main
    runtime: python3.10
    name: cosmos-to-s3-lambda-function
    role: iamRoleCosmosToS3LambdaFunction
    environment:
      COSMOS_CONNECTION_STRING: '{{resolve:secretsmanager:leonardo:SecretString:COSMOS_CONNECTION_STRING}}'
      S3_BUCKET_NAME: '{{resolve:secretsmanager:leonardo:SecretString:S3_BUCKET_NAME}}'
      DATABASE_NAME: cosmicworks
      CONTAINER_NAME: products
